// <auto-generated />
namespace OnlineFlightTicketBooking.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FlightV3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FlightV3));
        
        string IMigrationMetadata.Id
        {
            get { return "202003300729302_FlightV3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
